### ISSUE TITLE
A Suspected Issue with 1 of your Paid IPTV Recommendations

### ISSUE THREAD

**Issue by Den2Pies** [iptv-org/awesome-iptv#131]
Under the heading Providers/Paid you list BestBuyIPTV but be careful.
When I was looking for an IPTV source I came across these but looking on TrustPilot:-
https://www.trustpilot.com/review/bestbuyiptv.com
I became very suspicious and my suspicions were later confirmed with TroyPoint:-
https://troypoint.com/bestbuyiptv/
Also, they have multiple sites:-
https://bestbuyiptv.us/en2/?utm_medium=company_profile&utm_source=trustpilot&utm_campaign=domain_click
and always, the review is to treat with caution at best and more commonly, stay away.

If you want a recommendation you could add:-
https://bestiptvuk.me
I only had a day or two to sort. an IPTV provider before the British & Irish Lions rugby tour of South Africa was due to start.
I struck gold with these people. I have been with them for 10 months. They are not perfect but for the price I can truthfully say that they are damn good. Their free trial is farcical as it is 6 hours with no sports or only 2 hours with sports.
Also, and most important for me, they offer upto 7 days of catch-up on many UK and International streams.
cheersD
p.s. This is my 1st comment on Github so if you reply I may not know how to read you mail.

**Comment by jihedtlili** [comment]
Oui
