### ISSUE TITLE
Don't show any paid providers

### ISSUE THREAD

**Issue by evoactivity** [iptv-org/awesome-iptv#166]
The ones that are listed are clearly illegal and it comes across as a recommendation from the @iptv-org.

The org makes a large effort to maintain it's legality in other repos, including blacklisting specific channels being added to the DB and responding the DMCA notices.

In my opinion this list should be a one stop shop for developers and power users building for and using IPTV, not an advertisement for black market operators.

**Comment by MattTheTekie** [comment]
Be realistic, there are many *other awesome lists of other things* on GitHub, and elsewhere. I won't go into the other topic you said ffs.

**Comment by BellezaEmporium** [comment]
> The ones that are listed are clearly illegal and it comes across as a recommendation from the @iptv-org.
> 
> The org makes a large effort to maintain it's legality in other repos, including blacklisting specific channels being added to the DB and responding the DMCA notices.
> 
> In my opinion this list should be a one stop shop for developers and power users building for and using IPTV, not an advertisement for black market operators.

I understand your point of view, and it's interesting in many points.

However, our audience is seen more as a "provider" than a "base for programming/a developer tool", so it's clearly difficult to change ways drastically. We could show legal options, however I believe people aren't here for that (they try to escape from those options, mostly because of the price I think).

**Comment by mikhoul** [comment]
[**@BellezaEmporium**](https://github.com/BellezaEmporium) commented on [Apr 18, 2023, 6:47 AM EDT](https://github.com/iptv-org/awesome-iptv/issues/166#issuecomment-1512860629 "2023-04-18T10:47:23Z - Replied by Github Reply Comments"):
> > 
> ...mostly because of the price I think).

Exactly, if the price **and** services were fair there will be no need for "gray" market providers.

When Netflix begun with fair price  and a good services torrents use  diminished drastically, now that Netflix prices/services become poor values torrent begin to rise again. 

That's the invisible hand of capitalism at work... :octocat:

**Comment by MattTheTekie** [comment]
Thank you everyone for helping with my point. We all share these values, and it's important that we continue to bring this together.

**Comment by MattTheTekie** [comment]
:octocat:

**Comment by evoactivity** [comment]
The list is described as curated, suggesting there is some criteria to exceed for inclusion in the list. So what is the criteria that gets a provider added to the list? What have the current 4 done that the thousands of other providers haven't that makes them eligible for inclusion?

I'm not _trying_ to be argumentative for the sake of it, I just don't see an reason for why this list must include black market providers. This is the authoritive iptv org on github and to me there seems to be a disconnect between the aim to offer IPTV for free legally and also recommending black market providers. There are plenty of websites and forums for reviewing and recommending the black market providers that are more up to date, wider selection and generally will do a better job than what this list can do in terms of showing people what options are out there.

I could see a section that links to those review websites, forums and guides. I just don't see value in the 4 links offered in this list. They add extra risk for the repo (github already isn't happy with the org after the EPG debacle) without offering a huge amount of value to the users since the list is very incomplete.

**Comment by MattTheTekie** [comment]
> The list is described as curated, suggesting there is some criteria to exceed for inclusion in the list. So what is the criteria that gets a provider added to the list? What have the current 4 done that the thousands of other providers haven't that makes them eligible for inclusion?
> 
> I'm not _trying_ to be argumentative for the sake of it, I just don't see a reason for why this list must include black market providers. This is the authoritive iptv org on github and to me there seems to be a disconnect between the aim to offer IPTV for free legally and also recommending black market providers. There are plenty of websites and forums for reviewing and recommending the black market providers that are more up to date with wider selections. Generally they will do a better job than what this list can do in terms of showing people what options are out there.
> 
> I could see a section that links to those review websites, forums and guides. I just don't see value in the 4 links offered in this list. They add extra risk for the repo (github already isn't happy with the org after the EPG debacle) without offering a huge amount of value to the users since the list is very incomplete.

I'm not a developer in this project, but it's to appease the majority user base from what I can tell. As providers come and go over time, it's easier to use the big ones. I hope this can help.
