### ISSUE TITLE
Add NecroIPTV as Provider

### ISSUE THREAD

**Issue by NecronomiconCoding** [iptv-org/awesome-iptv#17]
These guys are trusted and exist since 2016

https://necroiptv.com

**Comment by freearhey** [comment]
Actually, since January 2017
<img width="322" alt="Screenshot 2019-10-24 at 08 00 12" src="https://user-images.githubusercontent.com/7253922/67454920-a21c3280-f634-11e9-8a92-7a0b4c224c1d.png">
