### ISSUE TITLE
Include Live TV for iOS and Android

### ISSUE THREAD

**Issue by cy8018** [iptv-org/awesome-iptv#210]
Live TV app is one of the best free IPTV player, import channels from M3U list, supports Picture-in-Picture, AirPlay, etc.

iOS:
https://apps.apple.com/app/live-tv-player/id6448868009

Android:
https://play.google.com/store/apps/details?id=com.cy8018.livetv

**Comment by BellezaEmporium** [comment]
Recently added in a pull request.
