### ISSUE TITLE
Proposal for Including TV.Garden in IPTV Stream Applications

### ISSUE THREAD

**Issue by TVGarden** [iptv-org/awesome-iptv#219]
Hello iptv-org team,

I would like to propose adding TV.Garden to the list of applications that support IPTV streams on this repository. TV.Garden is a fun project of mine, inspired by the concept of radio.garden. Just as radio.garden offers a convenient and enjoyable way to explore global radio stations, TV.Garden is designed to provide a similar experience for television streams. It enables convenient, easy, and reliable access to IPTV streams directly through the web, fully leveraging the streams provided by this incredible community.

### Project Details:
- **Name:** TV.Garden
- **Description:** TV.Garden is an inviting website that brings together IPTV streams, making it easy and fun to explore a wide variety of live content.
- **URL:** [TV.Garden](https://tv.garden)
- **Features:** TV.Garden offers seamless browsing with convenient filtering options, optimized for both mobile and desktop use. It exclusively utilizes iptv-org’s publicly accessible streams to ensure viewers have access to the latest content.

### Disclaimer:
I am the creator and maintainer of TV.Garden. This submission aims to provide additional value to the community by offering another platform through which users can access the extensive content provided by this incredible community.

I believe TV.Garden would be a valuable addition to your list, complementing the existing applications. Please let me know if there are any requirements or additional information needed to proceed with this inclusion.

I would also like to extend a heartfelt thank you to this community for providing the streams that power TV.Garden.

Thank you for considering this addition,
Martin
Creator, TV.Garden

**Comment by 1530-cell** [comment]
Thanks for tvgarden,  awesome.
