### ISSUE TITLE
Add IPTVChecker.py

### ISSUE THREAD

**Issue by NewsGuyTor** [iptv-org/awesome-iptv#238]
I just made a tool I think should be included:

https://github.com/NewsGuyTor/IPTVChecker/

<img width="794" alt="screenshot" src="https://github.com/user-attachments/assets/ffa84de1-f644-44b5-9d7d-92e32652a2be">

IPTV Stream Checker is a command-line tool designed to check the status of channels in an IPTV M3U8 playlist. It verifies if the streams are alive, captures screenshots, provides detailed information about video and audio streams, and identifies any potential issues like low framerates or mislabeled channels.

**Comment by PopeyeTheSai10r** [comment]
See https://github.com/iptv-org/awesome-iptv/blob/master/.github/CONTRIBUTING.md

**Comment by NewsGuyTor** [comment]
https://github.com/iptv-org/awesome-iptv/pull/243
