### ISSUE TITLE
MPC-HC

### ISSUE THREAD

**Issue by nu8** [iptv-org/awesome-iptv#34]
This works fine for IPTV, you just need to download the file first, you cant load directly from a URL:

https://github.com/clsid2/mpc-hc/releases

**Comment by I-Cat** [comment]
> This works fine for IPTV, you just need to download the file first, you cant load directly from a URL:
> 
> https://github.com/clsid2/mpc-hc/releases

Not an Issue?

**Comment by freearhey** [comment]
Added.
