### ISSUE TITLE
IPTV Collection Shutdown by Notice

### ISSUE THREAD

**Issue by NemoSciri** [iptv-org/awesome-iptv#39]
Please let me know if you need help getting it back up. The requester violated the fair use requirements as the URLs were in the public domain and available on the requesters own website.

**Comment by star600** [comment]
Yes please i would like to get the IPTV collection back I use it every day to watch IPTV. but how? Many thanks

**Comment by NemoSciri** [comment]
Are you the owner? Because of the nature of this, I can only help the owner.

**Comment by star600** [comment]
NO am not the owner

**Comment by NemoSciri** [comment]
Then cannot assist you in regards to this particular repository. Only the owner can request it be restored.

**Comment by star600** [comment]
Alright mate thank you.

**Comment by freearhey** [comment]
@NemoSciri Thank you for trying to help but I don't plan to support this project anymore.

However, if someone wants to publish playlists somewhere else they can do so, since this project originally implied that any person can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission.

Here is a link to download the latest version of the repository: https://gofile.io/d/KcdLaP

**Comment by star600** [comment]
Thanks you and good luck..

**Comment by SharyRajpoot** [comment]
Thank you and good luck...
I got your files but it only includes Channels by Country, how can I get it as Category and Language..?

**Comment by freearhey** [comment]
@SharyRajpoot All other files were generated using the script `scripts/generate.js`.

**Comment by SharyRajpoot** [comment]
Ok, thanks,
yes, I have already found those useful functions in the script folder. :-)

**Comment by Vel-San** [comment]
What was the Notice about tho? You weren't hosting anything, you were just providing means of access. Same as the tons and tons of streaming websites  that don't host anything on their servers. I believe you should open a support ticket and ask for the repo to be re-opened.

Such a shame this happened, does anybody have access to a different playlist? Even Fluxus got DMCAed.. Someone is hunting us out there!

**Comment by spencerthayer** [comment]
Where will IPTV org host their repository now? Pastebin?

**Comment by freearhey** [comment]
There are no plans to publish this repository somewhere else.

**Comment by Theitfixer85** [comment]
> @SharyRajpoot All other files were generated using the script `scripts/generate.js`.

Thanks for the script - Took me about an hour to set up the environment on windows to be able to run it and I had to make some edits to the generate and helper script for some reason you had it set to amend directory paths to .. which windows didn't like

**Comment by Daniel15** [comment]
>  Thank you for trying to help but I don't plan to support this project anymore.

Would you be willing to add new members to the `iptv-org` GitHub org so that they can take over the project? I think a DMCA counter-notice is justified in this case.

**Comment by freearhey** [comment]
@Daniel15 Yes, of course! Sent you an invite. 

Let me know if you need anything else.

**Comment by Daniel15** [comment]
Thank you @freearhey 

I just sent a DMCA counter notice. The company that submitted the DMCA notice has 14 days to respond, otherwise the repo will be reopened.

Here's what I sent:

> No infringing content is stored in this repository. The repository simply contains user-submitted links to publicly available video stream URLs, which to the best of our knowledge have been intentionally made publicly by the copyright holders. 
> 
> Furthermore, even if the content is in violation of copyright laws, simply linking to the content is not a valid reason to submit a DMCA request. Linking does not directly infringe copyright, because no copy is made on the site providing the link. See *Perfect 10, Inc. v. Google, Inc., 508 F.3d 1146*, *Perfect 10, Inc. v. Amazon.com, Inc., 508 F.3d 1146 (9th Cir. 2007)*, *Flava Works, Inc v. Gunter, 689 F.3d 754 (7th Cir. 2012)* and *Online Policy Group v. Diebold, Inc., 337 F.Supp.2d 1195, 1202 n.12 (N.D. Cal. 2004)* for prior caselaw, and https://ilt.eff.org/Copyright__Infringement_Issues.html#Linking for more information.
> 
> If any links to infringing content are found in this repo, they may be removed by sending a pull request or opening an issue.

**Comment by Daniel15** [comment]
@freearhey I heard back from GitHub:

> Thank you for submitting a DMCA counter notice. However, in order to process a counter notice for the disabled content, the notice must be submitted by an owner of the organization.

So either you need to submit it, or you need to make me an owner. I can give you the full text of my counter notice in GitHub's format if you'd like to submit it.

**Comment by Free-IPTV** [comment]
Was sind das denn für Vollpfosten von DFL Deutsche Fussball Liga e.V. .??? Es sind doch nur Stream-Adressen, die jeder frei empfangen kann.

**Comment by Free-IPTV** [comment]
> 
> 
> @NemoSciri Thank you for trying to help but I don't plan to support this project anymore.
> 
> However, if someone wants to publish playlists somewhere else they can do so, since this project originally implied that any person can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission.
> 
> Here is a link to download the latest version of the repository: https://gofile.io/d/KcdLaP

Thank you! :-)

**Comment by freearhey** [comment]
@Daniel15 Done, now you are the owner.

**Comment by Daniel15** [comment]
Thank you @freearhey. I just wrote back to GitHub.

**Comment by jonathasilva** [comment]
any ideia when the repository will be back up?

**Comment by Daniel15** [comment]
Counter-notice has been processed by Github: https://github.com/github/dmca/blob/master/2020/10/2020-10-08-dfl-counternotice.md

@jonathasilva It should be back within 9 days from today unless the complainant counters the counter notice.

**Comment by asrruban** [comment]
use this link on VLC
https://pasteli.org/8FZ4DEy7jJ
https://pasteli.org/download/8FZ4DEy7jJ

**Comment by zeg685** [comment]
Thank you for providing the files after the takedown, I wish you the best with your projects further ahead :D

**Comment by Free-IPTV** [comment]
Okay, i don't have as many lists to choose from as you do, but I do my best. I thank you too. :-)

**Comment by Ziad-84** [comment]
> Counter-notice has been processed by Github: https://github.com/github/dmca/blob/master/2020/10/2020-10-08-dfl-counternotice.md
> 
> @jonathasilva It should be back within 9 days from today unless the complainant counters the counter notice.

And? Ist it back?

**Comment by Daniel15** [comment]
@Ziad-84  I haven't heard back from GitHub yet. I'll ping them in a few days if I don't hear back.

**Comment by Daniel15** [comment]
It's back!

> Hi there,
> 
> As we did not hear back from the original submitter of the DMCA takedown notice that a court action has been filed to restrain the allegedly infringing content, we have restored the repository in accordance with our DMCA Counter Notice policy.
> 
> Let us know if we can assist further.
> 
> Thanks,
> GitHub Trust & Safety

🎉

**Comment by freearhey** [comment]
@Daniel15 Fantastic job! 🎉 You literally revived this project! ✨ Thank you very much!

**Comment by spencerthayer** [comment]
<hero>@Daniel15</hero>
