### ISSUE TITLE
Web IPTV

### ISSUE THREAD

**Issue by spencerthayer** [iptv-org/awesome-iptv#42]
Neither Jackal nor IPTV Player work. Is there an alternative?

**Comment by DUVVI** [comment]
Telugu m3u list please

**Comment by Mravuri96** [comment]
@spencerthayer Developer of IPTV-Player here, can you elaborate a little bit of the issues you are facing?

**Comment by mikhoul** [comment]
Nothing load here.

![image](https://user-images.githubusercontent.com/5678673/99275977-27532600-27fa-11eb-86e4-f512b6d4136c.png)

**Comment by spencerthayer** [comment]
> @spencerthayer Developer of IPTV-Player here, can you elaborate a little bit of the issues you are facing?

Is your code for the IPTV player open source @Mravuri96?

1. The URL https://iptv.maheshwarravuri.com doesn't reliably work. The load times are crazy. And right now I cannot actually load the site to find the specific error I was having. But I am going to keep trying so that I can be useful.
2. It requires the custom URL end in an M3U8. Most IPTV manager and providers don't rely on a live URL that ends in M3U8 making your player already incompatible with most URLS. For example the Fluxus IPTV url is https://pastebin.com/raw/hfRRAcpy. 
3. What @mikhoul said.

**Comment by Mravuri96** [comment]
@spencerthayer yes go to this repo [Mravuri96/IPTV-Player](https://github.com/Mravuri96/IPTV-Player), change branch to source.

**Comment by spencerthayer** [comment]
> @spencerthayer yes go to this repo [Mravuri96/IPTV-Player](https://github.com/Mravuri96/IPTV-Player), change branch to source.

AWESOME. I'll look at the code and submit some changes later this week. Thanks so much!

**Comment by DUVVI** [comment]
Telugu channels are not there in list
