### ISSUE TITLE
adding new channels

### ISSUE THREAD

**Issue by southerndream56** [iptv-org/awesome-iptv#46]
Hi,
Could you please add 4 Zambian channels in the „AFRICAN“ group,
ZNBC 1,ZNBC2,ZNBC3 and ZNBC 4?
Here are the links for LIVE streaming:

https://www.znbc.co.zm/live-tv-stream
https://www.znbc.co.zm/tv2-live-streaming
https://www.znbc.co.zm/tv3/live-tv-stream
https://www.znbc.co.zm/live-tv4

Thank you
Yours faithfully
Davor

**Comment by freearhey** [comment]
It would be better if you publish your request here: https://github.com/iptv-org/iptv/issues
This repository contains only links to IPTV related services.
