### ISSUE TITLE
WhatsUp TV app

### ISSUE THREAD

**Issue by WazaAU** [iptv-org/awesome-iptv#68]
Here is a links to WhatsUp TV app
Web: https://whatsuptv.app/
All Windows 10 devices including Xbox: https://www.microsoft.com/store/apps/9PGGVDSBTFVS
App store (iPhone) : https://apps.apple.com/us/app/whatsup-tv/id1476950273
Play store (Android): https://play.google.com/store/apps/details?id=au.com.deltaits.freewhatsuptv
Thank you.

**Comment by freearhey** [comment]
@WazaAU Added via d2cf41b
